#my module of listed Africa items: Fruits, countries and states

```python
africa_fruit = ["Mango", "Orange", "Banana", "Plantain", "Pineapple", "Pawpaw", "Watermelon", "Coconut", "Guava", "Apple", "Pear", "Grape", "Lemon", "Lime", "Tangerine", "Grapefruit", "Avocado", "Cashew Apple", "Cashew Nut", "African Star Apple", "Garden Egg", "African Pear", "Soursop", "Sugarcane", "Date Fruit", "Fig", "Cherry", "Strawberry", "Blueberry", "Raspberry", "Blackberry", "Cranberry", "Kiwi", "Passion Fruit", "Pomegranate", "Peach", "Plum", "Apricot", "Nectarine", "Lychee", "Longan", "Jackfruit", "Breadfruit", "Durian", "Rambutan", "Mangosteen", "Sapodilla", "Custard Apple", "Starfruit", "Mulberry", "Persimmon", "Quince", "Olive", "Almond", "Walnut", "Hazelnut", "Pistachio", "Macadamia", "Brazil Nut", "Tiger Nut", "Cola Nut", "Monkey Cola", "Velvet Tamarind", "Tamarind", "Hog Plum", "African Cherry", "African Mango", "African Nutmeg", "Balanites", "Baobab Fruit", "Wild Grape", "Sour Plum", "African Medlar", "Bush Mango", "African Breadfruit", "Snake Fruit", "Miracle Fruit", "Rose Apple", "June Plum", "Cloudberry", "Ackee"]
```
```python
african_countries = ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Republic", "Chad", "Comoros", "Democratic Republic of the Congo", "Republic of the Congo", "Djibouti", "Egypt", "Equatorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "The Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast (Côte d’Ivoire)", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "São Tomé and Príncipe", "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"]
```
africa_states = ["abuja","abia","adamawa","akwa ibom","anambra","bauchi","bayelsa","benue","borno","cross river","delta","ebonyi","edo","ekiti","enugu","gombe","imo","jigawa","kaduna","kano","katsina","kebbi","kogi","kwara","lagos","nasarawa","niger","ogun","ondo","osun","oyo","plateau","rivers","sokoto","taraba","yobe","zamfara","western cape","eastern cape","northern cape","free state","gauteng","kwazulu-natal","limpopo","mpumalanga","north west","cairo","giza","alexandria","aswan","aswan","asyut","beheira","beni suef","dakahlia","damietta","faiyum","gharbiya","ismailia","kafr el sheikh","luxor","matruh","minya","monufia","new valley","north sinai","port said","qalyubia","qena","red sea","sharqia","sohag","south sinai","suez","addis ababa","afar","amhara","benishangul-gumuz","dire dawa","gambela","harari","oromia","sidama","somali","south west ethiopia","southern nations","tigray","algiers","adrar","ain defla","ain temouchent","annaba","batna","bechar","bejaia","biskra","blida","bordj bou arreridj","bouira","boumerdes","chlef","constantine","djelfa","el bayadh","el oued","el tarf","ghardaia","guelma","illizi","jijel","khenchela","laghouat","m'sila","mascara","medea","mila","mostaganem","naama","oran","ouargla","oum el bouaghi","relizane","saida","setif","sidi bel abbes","skikda","soukh ahras","tamanrasset","tebessa","tiaret","tindouf","tipaza","tissemsilt","tizi ouzou","tlemcen","casablanca-settat","rabat-sale-kenitra","fes-meknes","marrakesh-safi","tangier-tetouan-al hoceima","oriental","beni mellal-khenifra","draa-tafilalet","souss-massa","laayoune-sakia el hamra","dakhla-oued ed dahab","ashanti","brong ahafo","central","eastern","greater accra","northern","north east","savannah","upper east","upper west","volta","oti","western","western north","nairobi","mombasa","kisumu","nakuru","uasin gishu","kiambu","muranga","nyeri","kirinyaga","embu","meru","machakos","makueni","kitui","kajiado","narok","bomet","kericho","nandi","kakamega","vihiga","bungoma","busia","siaya","homa bay","migori","kisii","nyamira","laikipia","nyandarua","turkana","west pokot","samburu","marsabit","isiolo","garissa","wajir","mandera","lamu","tana river","kilifi","kwale","taita taveta","tharaka nithi","elgeyo marakwet","baringo","trans nzoia","kampala","wakiso","mukono","jinja","mbale","gulu","lira","masaka","mbarara","kabale","fort portal","hoima","soroti","moroto","arua","lusaka","copperbelt","central","eastern","luapula","muchinga","northern","north western","southern","western","harare","bulawayo","manicaland","mashonaland central","mashonaland east","mashonaland west","masvingo","matabeleland north","matabeleland south","midlands","maputo","gaza","inhambane","sofala","manica","tete","zambezia","nampula","niassa","cabo delgado","luanda","bengo","benguela","bie","cabinda","cuando cubango","cunene","huila","kwanza norte","kwanza sul","luanda norte","luanda sul","malanje","moxico","namibe","uige","zaire"]
